# Generated by Django 4.2.4 on 2023-08-15 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.member')),
            ],
            bases=('members.member',),
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.member')),
            ],
            bases=('members.member',),
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.member')),
                ('last_name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.club')),
            ],
            bases=('members.member',),
        ),
    ]
