# Generated by Django 4.2.4 on 2024-01-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('date_start', models.DateTimeField(blank=True)),
                ('date_stop', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('do weryfikacji', 'do weryfikacji'), ('zaakceptowane', 'zaakceptowane'), ('odrzucone', 'odrzucone')], default='do weryfikacji', max_length=255)),
            ],
        ),
    ]
