# Generated by Django 4.2.4 on 2023-08-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swimming_facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_start', models.DateTimeField()),
                ('date_stop', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('swimming_facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimming_facilities.swimmingfacility')),
            ],
        ),
    ]
