# Generated by Django 4.2.4 on 2024-01-10 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swimming_facilities', '0001_initial'),
        ('users', '0001_initial'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='organiser_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organiser'),
        ),
        migrations.AddField(
            model_name='competition',
            name='swimming_facility_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swimming_facilities.swimmingfacility'),
        ),
    ]
