# Generated by Django 4.2.4 on 2023-10-19 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_club_organiser_competitor'),
        ('competitions', '0002_alter_competition_swimming_facility_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='organiser_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.organiser'),
        ),
    ]
