# Generated by Django 4.2.4 on 2023-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_club_organiser_competitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='competitor',
            name='first_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='last_name',
            field=models.CharField(max_length=75),
        ),
    ]
