# Generated by Django 4.2.4 on 2023-11-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimming_facilities', '0002_remove_swimmingfacility_organiser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmingfacility',
            name='pool_length',
            field=models.CharField(choices=[('25', 'Short'), ('50', 'Long')], default='25', max_length=10),
        ),
    ]
