# Generated by Django 4.2.4 on 2023-08-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_club_organiser_competitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwimmingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=45)),
                ('organiser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.organiser')),
            ],
        ),
    ]
