# Generated by Django 4.2.4 on 2023-10-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimming_facilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimmingfacility',
            name='organiser_id',
        ),
    ]
