# Generated by Django 4.2.4 on 2024-01-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('motylkowy', 'motylkowy'), ('grzbietowy', 'grzbietowy'), ('klasyczny', 'klasyczny'), ('dowolny', 'dowolny'), ('zmienny', 'zmienny')], default='motylkowy', max_length=255)),
                ('length', models.IntegerField(choices=[(25, '25'), (50, '50'), (100, '100'), (200, '200'), (400, '400'), (800, '800'), (1500, '1500')], default=25)),
                ('gender', models.BooleanField(default=True)),
            ],
        ),
    ]
