# Generated by Django 4.2.4 on 2023-10-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontype',
            name='length',
            field=models.CharField(choices=[('25', '25'), ('50', '50'), ('100', '100'), ('200', '200'), ('400', '400'), ('800', '800'), ('1500', '1500')], default='motylkowy', max_length=255),
        ),
        migrations.AddField(
            model_name='competitiontype',
            name='style',
            field=models.CharField(choices=[('motylkowy', 'motylkowy'), ('grzbietowy', 'grzbietowy'), ('klasyczny', 'klasyczny'), ('dowolny', 'dowolny'), ('zmienny', 'zmienny')], default='motylkowy', max_length=255),
        ),
    ]
