# Generated by Django 4.2.4 on 2023-10-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_types', '0002_competitiontype_length_competitiontype_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontype',
            name='length',
            field=models.CharField(choices=[('25', '25'), ('50', '50'), ('100', '100'), ('200', '200'), ('400', '400'), ('800', '800'), ('1500', '1500')], default='25', max_length=255),
        ),
    ]
