# Generated by Django 4.2.4 on 2023-10-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('competition_types', '0003_alter_competitiontype_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontype',
            name='competition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition'),
        ),
    ]
