# Generated by Django 4.2.4 on 2023-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_types', '0004_alter_competitiontype_competition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontype',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
