# Generated by Django 4.2.4 on 2023-08-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_club_organiser_competitor'),
        ('competitions', '0001_initial'),
        ('competition_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TimeField()),
                ('series_nr', models.IntegerField()),
                ('track_nr', models.IntegerField()),
                ('disqualification', models.BooleanField()),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('competition_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition_types.competitiontype')),
                ('competitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.competitor')),
            ],
        ),
    ]
