# Generated by Django 4.2.4 on 2024-01-10 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition_types', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TimeField(default=None, null=True)),
                ('series_nr', models.PositiveIntegerField(blank=True, null=True)),
                ('track_nr', models.PositiveIntegerField(blank=True, null=True)),
                ('disqualification', models.BooleanField(default=False)),
                ('place', models.PositiveIntegerField(default=None, null=True)),
                ('competition_type_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='competition_types.competitiontype')),
            ],
        ),
    ]
