# Generated by Django 4.2.4 on 2023-10-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0002_remove_participation_competition_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='competition_type_id',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='competitor_id',
        ),
    ]
