# Generated by Django 4.2.4 on 2023-10-05 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition_types', '0001_initial'),
        ('members', '0002_club_organiser_competitor'),
        ('participations', '0003_remove_participation_competition_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='competition_type_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='competition_types.competitiontype'),
        ),
        migrations.AddField(
            model_name='participation',
            name='competitor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='members.competitor'),
        ),
    ]
