# Generated by Django 4.2.4 on 2023-10-05 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition_types', '0003_alter_competitiontype_length'),
        ('participations', '0005_alter_participation_competition_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='competition_type_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='competition_types.competitiontype'),
        ),
    ]
