# Generated by Django 4.2.4 on 2023-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0007_alter_participation_competition_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='place',
            field=models.IntegerField(null=True),
        ),
    ]
