# Generated by Django 4.2.4 on 2023-11-18 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_name_member_username_competitor_first_name_and_more'),
        ('participations', '0010_alter_participation_place_alter_participation_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='competitor_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.competitor'),
        ),
    ]
