# Generated by Django 4.2.4 on 2023-11-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0011_alter_participation_competitor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='disqualification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participation',
            name='series_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='track_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
