# Generated by Django 4.2.4 on 2023-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competition_organiser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('do weryfikacji', 'do weryfikacji'), ('zaakceptowane', 'zaakceptowane'), ('odrzucone', 'odrzucone')], default='do weryfikacji', max_length=255),
        ),
    ]
