# Generated by Django 4.2.4 on 2023-11-18 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimming_facilities', '0003_swimmingfacility_pool_length'),
        ('competitions', '0004_alter_competition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date_stop',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='competition',
            name='swimming_facility_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swimming_facilities.swimmingfacility'),
        ),
    ]
